export const mission =
  "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse a nisi et velit volutpat interdum. Duis luctus nibh id odio semper, sit amet vulputate libero mollis. Sed ac lacus eget ex ullamcorper cursus non pretium quam. Sed metus enim, aliquam consequat porta sed, hendrerit non justo. Sed non felis accumsan, imperdiet ligula ac, fermentum nisi. Aenean eget venenatis justo, a lacinia turpis. Curabitur quis varius libero. Morbi in ligula orci. Integer neque orci, malesuada vitae lectus eget, cursus eleifend massa. Nullam pharetra, nisi nec efficitur iaculis, magna enim consectetur tellus, feugiat placerat dolor risus eget libero.";

export const vision =
  "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse a nisi et velit volutpat interdum. Duis luctus nibh id odio semper, sit amet vulputate libero mollis. Sed ac lacus eget ex ullamcorper cursus non pretium quam. Sed metus enim, aliquam consequat porta sed, hendrerit non justo. Sed non felis accumsan, imperdiet ligula ac, fermentum nisi. Aenean eget venenatis justo, a lacinia turpis. Curabitur quis varius libero. Morbi in ligula orci. Integer neque orci, malesuada vitae lectus eget, cursus eleifend massa. Nullam pharetra, nisi nec efficitur iaculis, magna enim consectetur tellus, feugiat placerat dolor risus eget libero.";

export const goals =
  "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse a nisi et velit volutpat interdum. Duis luctus nibh id odio semper, sit amet vulputate libero mollis. Sed ac lacus eget ex ullamcorper cursus non pretium quam. Sed metus enim, aliquam consequat porta sed, hendrerit non justo. Sed non felis accumsan, imperdiet ligula ac, fermentum nisi. Aenean eget venenatis justo, a lacinia turpis. Curabitur quis varius libero. Morbi in ligula orci. Integer neque orci, malesuada vitae lectus eget, cursus eleifend massa. Nullam pharetra, nisi nec efficitur iaculis, magna enim consectetur tellus, feugiat placerat dolor risus eget libero.";

export const objectives =
  "Pellentesque habitant morbi tPellentesque habitant morbi tristique senectus et netus et maPellentesque habitant morbi tristique senectus et netus et maristique senectus et netus et ma Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse a nisi et velit volutpat interdum. Duis luctus nibh id odio semper, sit amet vulputate libero mollis. Sed ac lacus eget ex ullamcorper cursus non pretium quam. Sed metus enim, aliquam consequat porta sed, hendrerit non justo. Sed non felis accumsan, imperdiet ligula ac, fermentum nisi. Aenean eget venenatis justo, a lacinia turpis. Curabitur quis varius libero. Morbi in ligula orci. Integer neque orci, malesuada vitae lectus eget, cursus eleifend massa. Nullam pharetra, nisi nec efficitur iaculis, magna enim consectetur tellus, feugiat placerat dolor risus eget libero.";
